### ISSUE TITLE
Interested in VB.NET

### ISSUE THREAD

**Issue by vexy1003** [prince0010/PoliceClearanceIssuanceSystemES#1]
Do you use some Framework in this Project? And if it is will you tell me what it is please?

**Comment by prince0010** [comment]
Hello! Yes, I used framework for this project and we used "Material2Framework" from DigitalAdeel, leocb and IgnaceMaes. You could see the github repo in my README.md

**Comment by prince0010** [comment]
> Do you use some Framework in this Project? And if it is will you tell me what it is please?

Hello! Yes, I used framework for this project and we used "Material2Framework" from DigitalAdeel, leocb and IgnaceMaes. You could see the github repo in my README.md

**Comment by prince0010** [comment]
> Do you use some Framework in this Project? And if it is will you tell me what it is please?

Hello! Yes, I used framework for this project and we used "Material2Framework" from DigitalAdeel, leocb and IgnaceMaes. You could see the github repo in my README.md
